version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: bt-search-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - bt-search-network
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:

networks:
  bt-search-network:
    driver: bridge
