services:
  db:
    image: postgis/postgis:15-3.3
    container_name: biotablero-postgis-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--auth-local=scram-sha-256"
      POSTGIS_GDAL_ENABLED_DRIVERS: ENABLE_ALL
      POSTGIS_ENABLE_OUTDB_RASTERS: "true"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/db/initdb:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      bash -c "apt-get update &&
               apt-get install -y postgresql-15-postgis-3 postgresql-15-postgis-3-scripts &&
               docker-entrypoint.sh postgres"

volumes:
  postgres_data:

networks:
  app-network: