"""Add column to test versioning system

Revision ID: 4a9907636eb3
Revises: bb6f68967bc7
Create Date: 2024-10-28 08:37:06.568341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a9907636eb3'
down_revision: Union[str, None] = 'bb6f68967bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_polygons', sa.Column('test_field', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric_polygons', 'test_field')
    # ### end Alembic commands ###
