"""add new column to test function

Revision ID: 7ce1d78f9087
Revises: bb6f68967bc7
Create Date: 2024-10-31 16:27:14.152380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ce1d78f9087'
down_revision: Union[str, None] = 'bb6f68967bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polygons', sa.Column('items_test', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polygons', 'items_test')
    # ### end Alembic commands ###
