name: Check code format

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Black format check
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./app"
